/** @type {import('tailwindcss').Config} */

const channel = (variable) => `rgb(var(${variable}) / <alpha-value>)`;

const fixedAlpha = (rgbVariable, opacityVariable) =>
  `rgb(var(${rgbVariable}) / var(${opacityVariable}))`;

export default {
  darkMode: ['selector', '[data-theme="dark"]'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        canvas: channel('--color-bg-canvas'),
        surface: channel('--color-bg-surface'),
        subtle: channel('--color-bg-subtle'),
        raised: channel('--color-bg-raised'),
        text: {
          primary: channel('--color-text-primary'),
          secondary: channel('--color-text-secondary'),
          muted: channel('--color-text-muted'),
          inverse: channel('--color-text-inverse'),
        },
        placeholder: channel('--color-placeholder'),
        border: {
          decorative: channel('--color-border-decorative'),
          control: channel('--color-border-control'),
          'control-hover': channel('--color-border-control-hover'),
          'control-focus': channel('--color-border-control-focus'),
        },
        'action-primary-bg': channel('--color-action-primary-bg'),
        'action-primary-text': channel('--color-action-primary-text'),
        'action-primary-border': channel('--color-action-primary-border'),
        'action-primary-hover-bg': channel('--color-action-primary-hover-bg'),
        'action-primary-active-bg': channel('--color-action-primary-active-bg'),
        'action-secondary-bg': channel('--color-action-secondary-bg'),
        'action-secondary-text': channel('--color-action-secondary-text'),
        'action-secondary-border': channel('--color-action-secondary-border'),
        'action-secondary-hover-bg': channel('--color-action-secondary-hover-bg'),
        'action-secondary-active-bg': channel('--color-action-secondary-active-bg'),
        'action-tertiary-bg': 'transparent',
        'action-tertiary-text': channel('--color-action-tertiary-text'),
        'action-tertiary-border': 'transparent',
        'action-tertiary-hover-bg': channel('--color-action-tertiary-hover-bg'),
        'action-tertiary-active-bg': channel('--color-action-tertiary-active-bg'),
        'action-danger-bg': channel('--color-action-danger-bg'),
        'action-danger-text': channel('--color-action-danger-text'),
        'action-danger-border': channel('--color-action-danger-border'),
        'action-danger-hover-bg': channel('--color-action-danger-hover-bg'),
        'action-danger-active-bg': channel('--color-action-danger-active-bg'),
        'action-disabled-bg': channel('--color-action-disabled-bg'),
        'action-disabled-text': channel('--color-action-disabled-text'),
        'action-disabled-border': channel('--color-action-disabled-border'),
        link: {
          DEFAULT: channel('--color-link-default'),
          hover: channel('--color-link-hover'),
          active: channel('--color-link-active'),
          visited: channel('--color-link-visited'),
          focus: channel('--color-link-focus'),
        },
        nav: {
          hover: channel('--color-nav-hover-bg'),
          selected: channel('--color-nav-selected-bg'),
          'selected-text': channel('--color-nav-selected-text'),
          indicator: channel('--color-nav-selected-indicator'),
        },
        icon: {
          DEFAULT: channel('--color-icon-default'),
          muted: channel('--color-icon-muted'),
          brand: channel('--color-icon-brand'),
          success: channel('--color-icon-success'),
          warning: channel('--color-icon-warning'),
          danger: channel('--color-icon-danger'),
          info: channel('--color-icon-info'),
        },
        focus: channel('--color-focus-ring'),
        disabled: {
          bg: channel('--color-disabled-bg'),
          text: channel('--color-disabled-text'),
          border: channel('--color-disabled-border'),
        },
        skeleton: {
          bg: channel('--color-skeleton-bg'),
          shimmer: channel('--color-skeleton-shimmer'),
        },
        neutral: {
          bg: channel('--color-neutral-bg'),
          text: channel('--color-neutral-text'),
          border: channel('--color-neutral-border'),
        },
        success: {
          bg: channel('--color-success-bg'),
          text: channel('--color-success-text'),
          border: channel('--color-success-border'),
        },
        warning: {
          bg: channel('--color-warning-bg'),
          text: channel('--color-warning-text'),
          border: channel('--color-warning-border'),
        },
        danger: {
          bg: channel('--color-danger-bg'),
          text: channel('--color-danger-text'),
          border: channel('--color-danger-border'),
        },
        info: {
          bg: channel('--color-info-bg'),
          text: channel('--color-info-text'),
          border: channel('--color-info-border'),
        },
        scrim: fixedAlpha('--color-scrim-rgb', '--opacity-scrim'),
        media: {
          control: fixedAlpha('--color-media-control-bg-rgb', '--opacity-media-control-bg'),
          text: channel('--color-media-control-text'),
          unplayed: channel('--color-media-track-unplayed'),
          played: channel('--color-media-track-played'),
          buffered: channel('--color-media-track-buffered'),
          outline: channel('--color-media-track-outline'),
          thumb: channel('--color-media-thumb-bg'),
          'thumb-border': channel('--color-media-thumb-border'),
        },
        chart: {
          1: channel('--color-chart-series-1'),
          2: channel('--color-chart-series-2'),
          3: channel('--color-chart-series-3'),
          4: channel('--color-chart-series-4'),
          5: channel('--color-chart-series-5'),
          grid: channel('--color-chart-grid'),
        },
      },
      fontFamily: {
        sans: ['Inter', '"Segoe UI"', 'Arial', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['2.5rem', { lineHeight: '3rem', fontWeight: '700' }],
        'display-sm': ['2.125rem', { lineHeight: '2.625rem', fontWeight: '700' }],
        'heading-1': ['1.875rem', { lineHeight: '2.375rem', fontWeight: '700' }],
        'heading-2': ['1.625rem', { lineHeight: '2.125rem', fontWeight: '700' }],
        'heading-3': ['1.375rem', { lineHeight: '1.875rem', fontWeight: '600' }],
        'heading-4': ['1.125rem', { lineHeight: '1.625rem', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75rem', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '400' }],
        'label-md': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '500' }],
        'label-sm': ['0.75rem', { lineHeight: '1rem', fontWeight: '600' }],
        caption: ['0.75rem', { lineHeight: '1rem', fontWeight: '400' }],
        button: ['0.875rem', { lineHeight: '1.25rem', fontWeight: '600' }],
      },
      spacing: {
        0: '0',
        0.5: '0.125rem',
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        8: '2rem',
        10: '2.5rem',
        12: '3rem',
        16: '4rem',
        20: '5rem',
        24: '6rem',
        32: '8rem',
      },
      borderRadius: {
        none: '0',
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      boxShadow: {
        subtle: '0 1px 2px rgb(16 24 40 / 0.05)',
        card: '0 4px 12px rgb(16 24 40 / 0.07)',
        dropdown: '0 12px 28px rgb(16 24 40 / 0.14)',
        modal: '0 24px 64px rgb(16 24 40 / 0.22)',
        navigation: '0 8px 24px rgb(16 24 40 / 0.08)',
      },
      transitionDuration: {
        instant: '0ms',
        fast: '120ms',
        base: '180ms',
        slow: '240ms',
      },
      maxWidth: {
        reading: '45rem',
        content: '75rem',
        dashboard: '90rem',
        marketing: '80rem',
        drawer: '20rem',
        tooltip: '20rem',
      },
      minWidth: {
        target: '2.75rem',
      },
      minHeight: {
        target: '2.75rem',
      },
      zIndex: {
        raised: '10',
        sticky: '20',
        dropdown: '30',
        drawer: '40',
        scrim: '45',
        modal: '50',
        popover: '60',
        toast: '70',
        tooltip: '80',
        'skip-link': '90',
      },
    },
  },
  plugins: [],
};
