import { useMemo, useState } from 'react';
import { Button, Card, FormField, Input } from '../../../components';
import { useVocabularyBookmark } from '../../student-productivity';
import { useStudentLessonVocabulary, useVocabularyLearningMutations } from '../hooks/use-student-player';
import type { StudentVocabulary } from '../types/student-player.types';

function WordCard({ item, onStatus }: { item: StudentVocabulary; onStatus: (value: 'KNOWN' | 'NEEDS_REVIEW') => void }) {
  const bookmark = useVocabularyBookmark(item.id);
  return <Card padding="lg" elevation="none"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-label-md">{item.turkishWord}</p><p className="mt-1 text-body-md">{item.uzbekMeaning}</p>{item.exampleSentence ? <p className="mt-2 text-body-sm text-text-secondary">{item.exampleSentence}</p> : null}<span className="mt-2 inline-flex rounded-full bg-subtle px-2 py-1 text-caption">{item.sourceStatus === 'REVIEW' ? 'REVIEW' : 'NEW'} · {item.learnerStatus === 'KNOWN' ? 'Bilaman' : 'Qayta ko‘raman'}</span></div><div className="flex flex-wrap gap-2"><Button intent="secondary" disabled={bookmark.isPending} onClick={bookmark.toggle}>{bookmark.isBookmarked ? 'Saqlangan' : 'Saqlash'}</Button><Button intent={item.learnerStatus === 'KNOWN' ? 'primary' : 'secondary'} onClick={() => onStatus('KNOWN')}>Bilaman</Button><Button intent={item.learnerStatus === 'NEEDS_REVIEW' ? 'primary' : 'secondary'} onClick={() => onStatus('NEEDS_REVIEW')}>Qayta ko‘raman</Button></div></div></Card>;
}

export function VocabularyLearningPanel({ enrollmentId, lessonId, enabled }: { enrollmentId: string; lessonId: string; enabled: boolean }) {
  const vocabulary = useStudentLessonVocabulary(enrollmentId, lessonId, enabled);
  const mutations = useVocabularyLearningMutations(enrollmentId, lessonId, enabled);
  const [mode, setMode] = useState<'learn' | 'flashcard' | 'practice' | 'test'>('learn');
  const [index, setIndex] = useState(0);
  const [revealed, setRevealed] = useState(false);
  const [attemptId, setAttemptId] = useState<string | null>(null);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [search, setSearch] = useState('');
  const [practiceDirection, setPracticeDirection] = useState<'TR_TO_UZ' | 'UZ_TO_TR'>('TR_TO_UZ');
  const [practiceAnswer, setPracticeAnswer] = useState<string | null>(null);
  const items = useMemo(() => vocabulary.data ?? [], [vocabulary.data]);
  const filtered = useMemo(() => items.filter((item) => `${item.turkishWord} ${item.uzbekMeaning}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())), [items, search]);
  const flash = filtered[index % Math.max(filtered.length, 1)];
  const practiceItem = filtered[index % Math.max(filtered.length, 1)];
  const practiceOptions = useMemo(() => practiceItem ? [practiceItem, ...filtered.filter((item) => item.id !== practiceItem.id).slice(0, 3)].sort(() => 0.5 - Math.random()) : [], [filtered, practiceItem]);
  const questions = mutations.start.data?.questions ?? [];
  const testResult = mutations.submit.data ?? mutations.latest.data;
  if (!enabled) return null;
  if (vocabulary.isPending) return <section className="mt-10"><h2 className="type-heading-2">Lug‘atlar</h2><p className="mt-4" role="status">Lug‘atlar yuklanmoqda...</p></section>;
  if (vocabulary.isError) return <p className="mt-6 text-body-sm text-warning-text" role="alert">Lug‘atlarni yuklab bo‘lmadi.</p>;
  if (!items.length) return <section className="mt-10"><h2 className="type-heading-2">Lug‘atlar</h2><p className="mt-4 text-body-sm text-text-secondary">Bu darsda lug‘at yozuvlari yo‘q.</p></section>;
  const beginTest = () => mutations.start.mutate(undefined, { onSuccess: (data) => { setAttemptId(data.attempt.id); setAnswers({}); } });
  const submitTest = () => { if (!attemptId) return; mutations.submit.mutate({ attemptId, answers: questions.map((question) => ({ vocabularyId: question.vocabularyId, submittedAnswer: answers[question.vocabularyId] ?? '' })) }, { onSuccess: () => setAttemptId(null) }); };
  return <section className="mt-10" aria-labelledby="vocabulary-heading"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="type-heading-2" id="vocabulary-heading">Lug‘atlar</h2><p className="mt-1 text-body-sm text-text-secondary">Mavzuning alohida so‘z o‘rganish bosqichi.</p></div><div className="flex flex-wrap gap-2" role="tablist"><Button intent={mode === 'learn' ? 'primary' : 'secondary'} onClick={() => setMode('learn')}>O‘rganish</Button><Button intent={mode === 'flashcard' ? 'primary' : 'secondary'} onClick={() => setMode('flashcard')}>Flashcard</Button><Button intent={mode === 'practice' ? 'primary' : 'secondary'} onClick={() => setMode('practice')}>Mashq</Button><Button intent={mode === 'test' ? 'primary' : 'secondary'} onClick={() => setMode('test')}>Lug‘at testi</Button></div></div>
    {mode === 'learn' ? <><Input aria-label="Lug‘atdan qidirish" className="mt-4" onChange={(event) => setSearch(event.target.value)} placeholder="Qidirish..." value={search} /><div className="mt-5 grid gap-3 sm:grid-cols-2">{filtered.map((item) => <WordCard item={item} key={item.id} onStatus={(value) => mutations.status.mutate({ vocabularyId: item.id, value })} />)}</div></> : null}
    {mode === 'flashcard' && flash ? <Card className="mt-5 text-center" padding="lg"><p className="text-caption text-text-muted">{index + 1} / {filtered.length}</p><p className="mt-5 text-heading-2">{revealed ? flash.uzbekMeaning : flash.turkishWord}</p><p className="mt-2 text-body-sm text-text-secondary">{revealed ? 'O‘zbekcha ma’no' : 'Javobni ko‘rish uchun bosing'}</p><Button className="mt-5" onClick={() => setRevealed((value) => !value)}>{revealed ? 'Turkchasini ko‘rish' : 'Javobni ko‘rish'}</Button><div className="mt-4 flex flex-wrap justify-center gap-2"><Button intent="secondary" onClick={() => { setIndex((value) => Math.max(0, value - 1)); setRevealed(false); }}>Oldingi</Button><Button intent="secondary" onClick={() => { mutations.status.mutate({ vocabularyId: flash.id, value: 'NEEDS_REVIEW' }); setIndex((value) => value + 1); setRevealed(false); }}>Qayta ko‘raman</Button><Button onClick={() => { mutations.status.mutate({ vocabularyId: flash.id, value: 'KNOWN' }); setIndex((value) => value + 1); setRevealed(false); }}>Bilaman</Button></div></Card> : null}
    {mode === 'practice' && practiceItem ? <Card className="mt-5" padding="lg"><div className="flex flex-wrap gap-2"><Button intent={practiceDirection === 'TR_TO_UZ' ? 'primary' : 'secondary'} onClick={() => { setPracticeDirection('TR_TO_UZ'); setPracticeAnswer(null); }}>Turkcha → O‘zbekcha</Button><Button intent={practiceDirection === 'UZ_TO_TR' ? 'primary' : 'secondary'} onClick={() => { setPracticeDirection('UZ_TO_TR'); setPracticeAnswer(null); }}>O‘zbekcha → Turkcha</Button></div><p className="mt-5 text-heading-3">{practiceDirection === 'TR_TO_UZ' ? practiceItem.turkishWord : practiceItem.uzbekMeaning}</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{practiceOptions.map((option) => { const value = practiceDirection === 'TR_TO_UZ' ? option.uzbekMeaning : option.turkishWord; const correct = value === (practiceDirection === 'TR_TO_UZ' ? practiceItem.uzbekMeaning : practiceItem.turkishWord); return <Button key={option.id} intent="secondary" onClick={() => { setPracticeAnswer(correct ? 'correct' : 'incorrect'); mutations.status.mutate({ vocabularyId: practiceItem.id, value: correct ? 'KNOWN' : 'NEEDS_REVIEW' }); }}>{value}</Button>; })}</div>{practiceAnswer ? <p className={`mt-4 font-semibold ${practiceAnswer === 'correct' ? 'text-success-text' : 'text-danger-text'}`} role="status">{practiceAnswer === 'correct' ? '✓ To‘g‘ri!' : `✕ Noto‘g‘ri. Javob: ${practiceDirection === 'TR_TO_UZ' ? practiceItem.uzbekMeaning : practiceItem.turkishWord}`}</p> : null}<Button className="mt-4" intent="secondary" onClick={() => { setIndex((value) => value + 1); setPracticeAnswer(null); }}>Keyingi so‘z</Button></Card> : null}
    {mode === 'test' ? <Card className="mt-5" padding="lg"><p className="text-body-md">Yo‘nalish: O‘zbekcha → Turkcha. O‘tish uchun kamida 75%.</p>{!attemptId && !mutations.start.data ? <Button className="mt-4" loading={mutations.start.isPending} onClick={beginTest}>Lug‘at testini boshlash</Button> : null}{attemptId ? <div className="mt-5 grid gap-5">{questions.map((question, questionIndex) => <FormField key={question.vocabularyId} label={`${questionIndex + 1}. ${question.prompt}`} required><Input onChange={(event) => setAnswers((current) => ({ ...current, [question.vocabularyId]: event.target.value }))} value={answers[question.vocabularyId] ?? ''} /></FormField>)}<Button disabled={questions.some((question) => !answers[question.vocabularyId]?.trim())} loading={mutations.submit.isPending} onClick={submitTest}>Testni topshirish</Button></div> : null}{testResult && !attemptId ? <div className="mt-5 rounded-lg bg-subtle p-4"><p className="text-label-md">Natija: {testResult.percentage}%</p><p className="mt-1 text-body-sm">{testResult.percentage >= 75 ? '✓ O‘zlashtirildi' : '✕ Qayta topshirish kerak'}</p><Button className="mt-3" intent="secondary" onClick={() => { mutations.start.reset(); setAttemptId(null); }}>Qayta topshirish</Button></div> : null}{mutations.start.isError ? <p className="mt-3 text-danger-text" role="alert">Bugungi lug‘at testi urinishlari tugagan yoki testni boshlashda xatolik yuz berdi.</p> : null}</Card> : null}
  </section>;
}
