import { RoleCode } from '@prisma/client';
import { AppError } from '../../utils/app-error.js';
import type { VocabularyLearningRepository } from './vocabulary-learning.repository.js';
import { VOCABULARY_PASSING_PERCENTAGE } from './vocabulary-learning.repository.js';
import type { LessonMasteryAccess } from '../lesson-mastery/lesson-mastery.types.js';

export class VocabularyLearningService {
  constructor(private readonly repository: VocabularyLearningRepository, private readonly masteryAccess?: LessonMasteryAccess) {}
  private async enrollment(enrollmentId: string, lessonId: string, actor: { userId: string; roles: RoleCode[] }) { if (!actor.roles.includes(RoleCode.STUDENT)) throw new AppError('Bu amal faqat student uchun.', 403, 'ACCESS_DENIED'); const row = await this.repository.assertEnrollment(enrollmentId, lessonId, actor.userId); if (!row) throw new AppError('Kurs enrollment’i topilmadi yoki unga kirish mumkin emas.', 403, 'ENROLLMENT_ACCESS_DENIED'); if (this.masteryAccess && !(await this.masteryAccess.canAccessEnrollmentLesson(enrollmentId, lessonId, actor.userId))) throw new AppError('Avval oldingi darsni o‘zlashtiring.', 403, 'LESSON_MASTERY_LOCKED'); return row; }
  async learning(enrollmentId: string, lessonId: string, actor: { userId: string; roles: RoleCode[] }) { await this.enrollment(enrollmentId, lessonId, actor); return this.repository.listLearning(actor.userId, lessonId); }
  async status(enrollmentId: string, lessonId: string, vocabularyId: string, value: 'KNOWN' | 'NEEDS_REVIEW', actor: { userId: string; roles: RoleCode[] }) { await this.enrollment(enrollmentId, lessonId, actor); const result = await this.repository.updateStatus(actor.userId, lessonId, vocabularyId, value); if (!result) throw new AppError('Lug‘at yozuvi topilmadi.', 404, 'VOCABULARY_NOT_FOUND'); return result; }
  async test(enrollmentId: string, lessonId: string, actor: { userId: string; roles: RoleCode[] }) { await this.enrollment(enrollmentId, lessonId, actor); const result = await this.repository.latestResult(enrollmentId, lessonId); return { lessonId, passingPercentage: VOCABULARY_PASSING_PERCENTAGE, latestResult: result }; }
  async start(enrollmentId: string, lessonId: string, actor: { userId: string; roles: RoleCode[] }) { await this.enrollment(enrollmentId, lessonId, actor); if (await this.repository.countFailedAttemptsToday(enrollmentId, lessonId) >= 3) throw new AppError('Bugungi lug‘at testi urinishlari tugadi. Ertaga yana urinib ko‘ring.', 429, 'VOCABULARY_DAILY_LIMIT_REACHED'); const selected = await this.repository.listTestItems(lessonId); if (!selected.length) throw new AppError('Bu darsda lug‘at test savollari mavjud emas.', 409, 'VOCABULARY_EMPTY'); const open = await this.repository.findOpenAttempt(enrollmentId, lessonId); const attempt = open ?? await this.repository.createAttempt(enrollmentId, lessonId, selected); const questions = await this.repository.attemptQuestions(attempt.id); return { attempt: { ...attempt, startedAt: attempt.startedAt.toISOString(), submittedAt: attempt.submittedAt?.toISOString() ?? null }, questions: questions.map((item) => ({ vocabularyId: item.vocabularyId, prompt: item.vocabulary.uzbekMeaning, direction: 'UZ_TO_TR_TYPED' as const })) }; }
  async submit(enrollmentId: string, lessonId: string, attemptId: string, answers: Array<{ vocabularyId: string; submittedAnswer: string }>, actor: { userId: string; roles: RoleCode[] }) { await this.enrollment(enrollmentId, lessonId, actor); const attempt = await this.repository.findAttempt(attemptId, enrollmentId, lessonId); if (!attempt) throw new AppError('Lug‘at testi urinishi topilmadi.', 404, 'VOCABULARY_ATTEMPT_NOT_FOUND'); const selected = await this.repository.attemptQuestions(attemptId); if (new Set(answers.map((a) => a.vocabularyId)).size !== answers.length || answers.length !== selected.length || answers.some((a) => !selected.some((q) => q.vocabularyId === a.vocabularyId))) throw new AppError('Lug‘at testi javoblari to‘liq emas.', 422, 'VOCABULARY_ANSWERS_INVALID'); const result = await this.repository.submitAttempt(attemptId, selected.map((item) => ({ vocabularyId: item.vocabularyId, turkishWord: item.vocabulary.turkishWord })), answers); if (!result) throw new AppError('Lug‘at testi urinishi yuborilmadi.', 409, 'VOCABULARY_ATTEMPT_CONFLICT'); return result; }
  async latest(enrollmentId: string, lessonId: string, actor: { userId: string; roles: RoleCode[] }) { await this.enrollment(enrollmentId, lessonId, actor); return this.repository.latestResult(enrollmentId, lessonId); }
}
